### ISSUE TITLE
Discord Sidebar: Failure to remember login

### ISSUE THREAD

**Issue by ml-dp** [semanticdata/browser-extensions#3]
As title suggest. Everytime we close out and re-enter discord, it seems we are automatically logged off.

**Comment by semanticdata** [comment]
Hey @cafelinked,

I tried to replicate a few different situations but I haven't encountered this issue. Using a new Firefox installation, and my current config seems to be working as intended.

When it happens, are you being logged out of the full Discord Webapp as well as the sidebar? If you are, that might indicate a problem with your cookies/cache retention, not necessarily with the extension.

Hope this helps.
